computerPlay //randomly selects computers move
playRound //two parameters (player selection, computer selection) Will return string for win/loss.
//case insensitive

/*Test if the above is working with:
const playerSelection = "rock";
const computerSelection = computerPlay();
console.log(playRound(playerSelection, computerSelection));
*/

function game() //call playRound within this to play 5 games, record score, and declare winner.
/*use loops
for (let i = 0; i < 5; i++) {
   // your code here!
}*/

//use console log to declare winner from each round.
